[package]
name = "twpb_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = {version="1.0.57",features=["full","fold","extra-traits"]}
quote = "1.0.15"
heapless = "0.7.10"
anyhow = "1.0.53"
paste = "1.0.6"
proc-macro2 = "1.0.36"